# Generated by Django 4.2.4 on 2023-09-11 20:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivosFijos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('modelo', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
                ('vida_util', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100, message='La vida útil no puede ser mayor a 100 años')])),
                ('valor_unitario', models.DecimalField(decimal_places=10, max_digits=20)),
                ('flete', models.DecimalField(decimal_places=2, max_digits=10)),
                ('placa_amva', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999999999999999999999999999999999999999999999)])),
                ('observaciones', models.TextField(validators=[django.core.validators.MaxLengthValidator(500, message='Las observaciones no pueden exceder los 500 caracteres')])),
                ('foto', models.ImageField(blank=True, null=True, upload_to='activos_fijos/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tipo_activo', models.CharField(default='activo_fijo', editable=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(validators=[django.core.validators.MaxLengthValidator(500, message='Las observaciones no pueden exceder los 500 caracteres')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(validators=[django.core.validators.MaxLengthValidator(500, message='Las observaciones no pueden exceder los 500 caracteres')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField(validators=[django.core.validators.MaxLengthValidator(500, message='Las observaciones no pueden exceder los 500 caracteres')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(validators=[django.core.validators.MaxLengthValidator(500, message='Las observaciones no pueden exceder los 500 caracteres')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(validators=[django.core.validators.MaxLengthValidator(500)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoActivosFijos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
                ('descripcion', models.TextField(validators=[django.core.validators.MaxLengthValidator(500)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoriva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descripcion', models.TextField(validators=[django.core.validators.MaxLengthValidator(500, message='Las observaciones no pueden exceder los 500 caracteres')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(validators=[django.core.validators.MaxLengthValidator(500, message='Las observaciones no pueden exceder los 500 caracteres')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nit', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999999999999999999999999999999999999999999999)])),
                ('telefono', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999999999999999999999999999999999999999999999)])),
                ('correo', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedMonitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(validators=[django.core.validators.MaxLengthValidator(500)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(validators=[django.core.validators.MaxLengthValidator(500, message='Las observaciones no pueden exceder los 500 caracteres')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoActivosFijos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('codigo_estacion', models.CharField(max_length=20)),
                ('convenio', models.CharField(max_length=50)),
                ('placa_amva', models.CharField(default='ValorPredeterminado', max_length=20)),
                ('barrio', models.CharField(max_length=100)),
                ('cuenca', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=10)),
                ('descripcion', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('activo_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sibi.activosfijos')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.dependencia')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.municipio')),
                ('red_monitoreo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.redmonitoreo')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.BigIntegerField(unique=True)),
                ('fecha_factura', models.DateField()),
                ('numero_contrato', models.BigIntegerField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Consumibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_ingreso', models.DateField()),
                ('modelo', models.CharField(max_length=100)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flete', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(validators=[django.core.validators.MaxLengthValidator(500, message='Las observaciones no pueden exceder los 500 caracteres')])),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='consumibles/')),
                ('numero_convenio', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tipo_activo', models.CharField(default='consumible', editable=False, max_length=20)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.articulo')),
                ('cartera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.cartera')),
                ('categoria_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.categoriaproducto')),
                ('factura_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.facturacontrato')),
                ('iva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.iva')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.marca')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.moneda')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.proveedor')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.referencia')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.ubicacion')),
            ],
        ),
        migrations.AddField(
            model_name='activosfijos',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.articulo'),
        ),
        migrations.AddField(
            model_name='activosfijos',
            name='cartera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.cartera'),
        ),
        migrations.AddField(
            model_name='activosfijos',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.control'),
        ),
        migrations.AddField(
            model_name='activosfijos',
            name='estado_hisorial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sibi.estadoactivosfijos'),
        ),
        migrations.AddField(
            model_name='activosfijos',
            name='factura_contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.facturacontrato'),
        ),
        migrations.AddField(
            model_name='activosfijos',
            name='iva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.iva'),
        ),
        migrations.AddField(
            model_name='activosfijos',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.marca'),
        ),
        migrations.AddField(
            model_name='activosfijos',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.moneda'),
        ),
        migrations.AddField(
            model_name='activosfijos',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.proveedor'),
        ),
        migrations.AddField(
            model_name='activosfijos',
            name='referencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.referencia'),
        ),
        migrations.AddField(
            model_name='activosfijos',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.ubicacion'),
        ),
    ]
