# Generated by Django 4.2.4 on 2023-08-04 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sibi', '0002_activosfijos_is_active_articulo_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activosfijos',
            name='campo',
        ),
    ]
