# Generated by Django 4.2.4 on 2023-08-04 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sibi', '0003_remove_activosfijos_campo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_ingreso', models.DateField()),
                ('numero_factura', models.CharField(max_length=50)),
                ('fecha_factura', models.DateField()),
                ('numero_contrato', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flete', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField()),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='consumibles/')),
                ('numero_convenio', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.articulo')),
                ('cartera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.cartera')),
                ('categoria_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.categoriaproducto')),
                ('iva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.iva')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.marca')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.moneda')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.proveedor')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.referencia')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.ubicacion')),
            ],
        ),
    ]
