# Generated by Django 4.2.4 on 2023-08-05 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibi', '0004_consumibles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activosfijos',
            name='fecha_factura',
        ),
        migrations.AlterField(
            model_name='activosfijos',
            name='numero_contrato',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_number', message='El número de contrato debe ser un número entero', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='activosfijos',
            name='numero_factura',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_number', message='El número de factura debe ser un número entero', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='activosfijos',
            name='observaciones',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(500, message='Las observaciones no pueden exceder los 500 caracteres')]),
        ),
        migrations.AlterField(
            model_name='activosfijos',
            name='placa_amva',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_number', message='La placa AMVA debe ser un número entero', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='activosfijos',
            name='vida_util',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100, message='La vida útil no puede ser mayor a 100 años')]),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='descripcion',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(200, message='La descripción no puede exceder los 200 caracteres')]),
        ),
        migrations.AlterField(
            model_name='cartera',
            name='descripcion',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(200, message='La descripción no puede exceder los 200 caracteres')]),
        ),
        migrations.AlterField(
            model_name='categoriaproducto',
            name='descripcion',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(200, message='La descripción no puede exceder los 200 caracteres')]),
        ),
        migrations.AlterField(
            model_name='consumibles',
            name='numero_contrato',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_number', message='El número de contrato debe ser un número entero', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='consumibles',
            name='numero_factura',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_number', message='El número de factura debe ser un número entero', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='consumibles',
            name='observaciones',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(500, message='Las observaciones no pueden exceder los 500 caracteres')]),
        ),
        migrations.AlterField(
            model_name='control',
            name='descripcion',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(200, message='La descripción no puede exceder los 200 caracteres')]),
        ),
        migrations.AlterField(
            model_name='iva',
            name='descripcion',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(200, message='La descripción no puede exceder los 200 caracteres')]),
        ),
        migrations.AlterField(
            model_name='marca',
            name='descripcion',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(200, message='La descripción no puede exceder los 200 caracteres')]),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='tipo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_number', message='El NIT debe ser un número entero', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_number', message='El teléfono debe ser un número entero', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='lugar',
            field=models.CharField(max_length=20),
        ),
    ]
