# Generated by Django 4.2.4 on 2023-08-05 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibi', '0005_remove_activosfijos_fecha_factura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activosfijos',
            name='numero_contrato',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999999999999999999999999999999999999999999999)]),
        ),
        migrations.AlterField(
            model_name='activosfijos',
            name='numero_factura',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999999999999999999999999999999999999999999999)]),
        ),
        migrations.AlterField(
            model_name='activosfijos',
            name='placa_amva',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999999999999999999999999999999999999999999999)]),
        ),
        migrations.AlterField(
            model_name='consumibles',
            name='numero_contrato',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999999999999999999999999999999999999999999999)]),
        ),
        migrations.AlterField(
            model_name='consumibles',
            name='numero_factura',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999999999999999999999999999999999999999999999)]),
        ),
    ]
