# Generated by Django 4.2.4 on 2023-08-05 22:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibi', '0007_alter_activosfijos_valor_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencia',
            name='descripcion',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(200, message='La descripción no puede exceder los 200 caracteres')]),
        ),
    ]
