# Generated by Django 4.2.4 on 2023-08-05 23:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibi', '0008_alter_referencia_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='descripcion',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(500, message='Las observaciones no pueden exceder los 500 caracteres')]),
        ),
        migrations.AlterField(
            model_name='cartera',
            name='descripcion',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(500, message='Las observaciones no pueden exceder los 500 caracteres')]),
        ),
        migrations.AlterField(
            model_name='categoriaproducto',
            name='descripcion',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(500, message='Las observaciones no pueden exceder los 500 caracteres')]),
        ),
        migrations.AlterField(
            model_name='control',
            name='descripcion',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(500, message='Las observaciones no pueden exceder los 500 caracteres')]),
        ),
        migrations.AlterField(
            model_name='iva',
            name='descripcion',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(500, message='Las observaciones no pueden exceder los 500 caracteres')]),
        ),
        migrations.AlterField(
            model_name='marca',
            name='descripcion',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(500, message='Las observaciones no pueden exceder los 500 caracteres')]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999999999999999999999999999999999999999999999)]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999999999999999999999999999999999999999999999)]),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='descripcion',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(500, message='Las observaciones no pueden exceder los 500 caracteres')]),
        ),
    ]
