# Generated by Django 4.2.4 on 2023-08-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibi', '0009_alter_articulo_descripcion_alter_cartera_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activosfijos',
            name='tipo_activo',
            field=models.CharField(default='activo_fijo', max_length=20),
        ),
        migrations.AddField(
            model_name='consumibles',
            name='tipo_activo',
            field=models.CharField(default='consumible', max_length=20),
        ),
    ]
