# Generated by Django 4.2.4 on 2023-08-23 23:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibi', '0010_activosfijos_tipo_activo_consumibles_tipo_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoActivosFijos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
                ('descripcion', models.TextField(validators=[django.core.validators.MaxLengthValidator(500)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='activosfijos',
            name='cantidad',
        ),
        migrations.AlterField(
            model_name='activosfijos',
            name='tipo_activo',
            field=models.CharField(default='activo_fijo', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='consumibles',
            name='tipo_activo',
            field=models.CharField(default='consumible', editable=False, max_length=20),
        ),
    ]
