# Generated by Django 4.2.4 on 2023-08-24 00:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sibi', '0011_estadoactivosfijos_remove_activosfijos_cantidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(validators=[django.core.validators.MaxLengthValidator(500)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedMonitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(validators=[django.core.validators.MaxLengthValidator(500)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialActivosFijos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('codigo_estacion', models.CharField(max_length=20)),
                ('convenio', models.CharField(max_length=50)),
                ('placa_amva', models.CharField(max_length=20)),
                ('barrio', models.CharField(max_length=100)),
                ('cuenca', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=10)),
                ('descripcion', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('activo_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sibi.activosfijos')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.dependencia')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.municipio')),
                ('red_monitoreo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibi.redmonitoreo')),
            ],
        ),
    ]
