# Generated by Django 4.2.4 on 2023-08-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sibi', '0012_departamento_dependencia_redmonitoreo_municipio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialactivosfijos',
            name='placa_amva',
        ),
    ]
