# Generated by Django 4.2.4 on 2023-08-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sibi', '0013_remove_historialactivosfijos_placa_amva'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistorialActivosFijos',
            new_name='HistoricoActivosFijos',
        ),
    ]
