# Generated by Django 4.2.4 on 2023-08-31 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sibi', '0014_rename_historialactivosfijos_historicoactivosfijos'),
    ]

    operations = [
        migrations.AddField(
            model_name='activosfijos',
            name='estado_hisorial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sibi.estadoactivosfijos'),
        ),
    ]
